### ISSUE TITLE
Get the _id assigned to an object right after inserting it

### ISSUE THREAD

**Issue by greenled** [ylemoigne/mongo-jackson-codec#6]
Hi. Is it possible to get the `_id` assigned to an object right after inserting it? All I get is null :(

``` java
Item item = new Item();
database.getCollection("items", Item.class).insertOne(item);
System.out.println(item.id); // null
```

I am looking for something like http://stackoverflow.com/a/3339206/2636418, but for custom objects with codecs, not for BasicDBObject. Any idea?

**Comment by ylemoigne** [comment]
Sorry, It does not seem possible. (If it is, it's not trivial)

As a workaround, the best I can offer is to use `@Id` on a String field, and initialize this field with something like `java.util.UUID.randomUUID().toString()`. This way your object have an id before being inserted.
